# Generated by Django 5.0.7 on 2024-07-16 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
